# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fcp < Formula
  desc "Copy data from/to farcaster and the local filesystem"
  homepage "https://github.com/vrypan/fcp"
  version "0.9.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vrypan/fcp/releases/download/v0.9.6/fcp_Darwin_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "603a1856aaa5c877b7323e277b62c52d1cdda4c0a7b2589f86058dca8e4f3102"

      def install
        bin.install "fcp"
        bin.install "fcp-inspect"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vrypan/fcp/releases/download/v0.9.6/fcp_Darwin_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "da54e93482fe8c96e2553210ab27eda705e5c12c870b38a744182c7f24f21a62"

      def install
        bin.install "fcp"
        bin.install "fcp-inspect"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vrypan/fcp/releases/download/v0.9.6/fcp_Linux_x86_64.tar.gz",
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "35bf17019f711fe688e8d65589d44109b48eb65465e9df268ac0057db000eb18"

        def install
          bin.install "fcp"
          bin.install "fcp-inspect"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vrypan/fcp/releases/download/v0.9.6/fcp_Linux_arm64.tar.gz",
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "5c07d95aa00a62b0be11f923eeb51afab0050ae735293839945f35f54efce5e9"

        def install
          bin.install "fcp"
          bin.install "fcp-inspect"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Both binaries have been installed:
        - fcp → `fcp --help`
        - fcp-inspect → `fcp-inspect --help`
    EOS
  end

  test do
    system "#{bin}/fcp --version"
    system "#{bin}/fcp-inspect --version"
  end
end
