# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fcp < Formula
  desc "Copy data from/to farcaster and the local filesystem"
  homepage "https://github.com/vrypan/fcp"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vrypan/fcp/releases/download/v1.0.2/fcp_Darwin_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "7208b7f77bd346fc6c2f34e284c521c0fc09ed10adf4be84d465e534fada4b94"

      def install
        bin.install "fcp"
        bin.install "fcp-inspect"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vrypan/fcp/releases/download/v1.0.2/fcp_Darwin_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "9fea7a17fd4a5c90ed32b6e0aff918bef917f97dedd63134922732d9bfd123bd"

      def install
        bin.install "fcp"
        bin.install "fcp-inspect"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/vrypan/fcp/releases/download/v1.0.2/fcp_Linux_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "42497d200b5b40fedca61002095ccf5dffae44c58043d562608e1cec6c3c0d52"
      def install
        bin.install "fcp"
        bin.install "fcp-inspect"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/vrypan/fcp/releases/download/v1.0.2/fcp_Linux_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "872c8aeda2a19ff79bee78c85b31441b5a7f4d49e19f3b772b5fd249305d6c14"
      def install
        bin.install "fcp"
        bin.install "fcp-inspect"
      end
    end
  end

  def caveats
    <<~EOS
      Both binaries have been installed:
        - fcp → `fcp --help`
        - fcp-inspect → `fcp-inspect --help`
    EOS
  end

  test do
    system "#{bin}/fcp --version"
    system "#{bin}/fcp-inspect --version"
  end
end
