# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fcp < Formula
  desc "Copy data from/to farcaster and the local filesystem"
  homepage "https://github.com/vrypan/fcp"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vrypan/fcp/releases/download/v1.0.0/fcp_Darwin_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "1e3e00da9b98449cd21ddfde26dc639d48400e4dd6a63581acce9820f5e1071e"

      def install
        bin.install "fcp"
        bin.install "fcp-inspect"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vrypan/fcp/releases/download/v1.0.0/fcp_Darwin_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "beac5a713ddb1308ae79df6bc2a3dfb47dab09d8fe7604cf2ff604ff6f6f9e56"

      def install
        bin.install "fcp"
        bin.install "fcp-inspect"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vrypan/fcp/releases/download/v1.0.0/fcp_Linux_x86_64.tar.gz",
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "1f9e5ce1e381a5b0607e5f0c2d065948e287e108287052ea5bfadf221c3dc033"

        def install
          bin.install "fcp"
          bin.install "fcp-inspect"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vrypan/fcp/releases/download/v1.0.0/fcp_Linux_arm64.tar.gz",
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "b81e7a6ec173444e5437aa980b1a2b7c56df7f82c29f4aa4555b4f2e4d7ea77e"

        def install
          bin.install "fcp"
          bin.install "fcp-inspect"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Both binaries have been installed:
        - fcp → `fcp --help`
        - fcp-inspect → `fcp-inspect --help`
    EOS
  end

  test do
    system "#{bin}/fcp --version"
    system "#{bin}/fcp-inspect --version"
  end
end
